// template/Enums.js — Generates shared Swift enum types from enum properties

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { toSwiftEnumCase, setTypePrefix, setAllowNameCollisions } = require('../helpers/swift');
const { extractEnums } = require('../helpers/schema');

function Enums({ asyncapi, params }) {
  setTypePrefix(params?.typePrefix);
  setAllowNameCollisions(params?.allowNameCollisions);
  const enums = extractEnums(asyncapi);
  if (enums.length === 0) return null;

  const enumBlocks = enums.map(e => {
    const cases = e.values.map(v => {
      const caseName = toSwiftEnumCase(v);
      const cleanCase = caseName.replace(/`/g, '');
      if (e.rawType === 'Int') {
        return `    case ${caseName} = ${v}`;
      }
      if (cleanCase !== String(v)) {
        return `    case ${caseName} = "${v}"`;
      }
      return `    case ${caseName}`;
    });

    return `public enum ${e.swiftName}: ${e.rawType}, Codable, Sendable {
${cases.join('\n')}
}`;
  });

  return (
    <File name="Sources/Enums.swift">
      <Text>{`// Generated by asyncapi-swift-ws-template — do not edit
import Foundation

${enumBlocks.join('\n\n')}`}</Text>
    </File>
  );
}

module.exports = Enums;
