// template/MessageEnums.js — Generates IncomingMessage and OutgoingMessage tagged enums

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { toSwiftEnumCase, toSwiftPropertyName, prefixedName, setTypePrefix, setAllowNameCollisions } = require('../helpers/swift');
const { extractMessages } = require('../helpers/schema');

function MessageEnums({ asyncapi, params }) {
  setTypePrefix(params?.typePrefix);
  setAllowNameCollisions(params?.allowNameCollisions);
  const useMsgpack = params?.serialization === 'msgpack';
  const msgpackArray = useMsgpack && params?.msgpackFormat === 'array';
  const allMessages = extractMessages(asyncapi);

  const sendMessages = allMessages.filter(m => m.direction === 'send');
  const receiveMessages = allMessages.filter(m => m.direction === 'receive');

  const outgoingName = prefixedName('OutgoingMessage');
  const incomingName = prefixedName('IncomingMessage');

  const lines = [];
  lines.push('// Generated by asyncapi-swift-ws-template — do not edit');
  lines.push('import Foundation');
  lines.push('');

  // ── OutgoingMessage ──
  if (sendMessages.length > 0) {
    lines.push('/// Messages the client can send to the server.');
    lines.push(`public enum ${outgoingName}: Sendable {`);
    for (const msg of sendMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      if (msg.hasObjectPayload) {
        lines.push(`    case ${caseName}(${msg.swiftName})`);
      } else {
        lines.push(`    case ${caseName}(String)`);
      }
    }
    lines.push('}');
    lines.push('');

    // Encodable conformance
    lines.push(`extension ${outgoingName}: Encodable {`);
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push('        switch self {');
    for (const msg of sendMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      if (msg.hasObjectPayload) {
        lines.push(`        case .${caseName}(let value):`);
        lines.push('            try value.encode(to: encoder)');
      } else {
        lines.push(`        case .${caseName}(let value):`);
        lines.push('            var container = encoder.singleValueContainer()');
        lines.push('            try container.encode(value)');
      }
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  // ── IncomingMessage ──
  if (receiveMessages.length > 0) {
    // Separate object-payload messages from plain-value messages for decoding strategy
    const objectReceive = receiveMessages.filter(m => m.hasObjectPayload);
    const plainReceive = receiveMessages.filter(m => !m.hasObjectPayload);

    lines.push('/// Messages the client can receive from the server.');
    lines.push(`public enum ${incomingName}: Sendable {`);
    for (const msg of receiveMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      if (msg.hasObjectPayload) {
        lines.push(`    case ${caseName}(${msg.swiftName})`);
      } else {
        lines.push(`    case ${caseName}(String)`);
      }
    }
    lines.push('    case unknown(String)');
    lines.push('}');
    lines.push('');

    // Decodable conformance — discriminated on detected const field for object messages,
    // plain string matching for non-object messages
    lines.push(`extension ${incomingName}: Decodable {`);

    // Determine the discriminator key from object receive messages
    const detectedKeys = objectReceive.map(m => m.discriminatorKey).filter(Boolean);
    const discriminatorKey = detectedKeys[0] || 'type';
    // Convert to camelCase for Swift CodingKey case name (without keyword escaping)
    const swiftKeyName = discriminatorKey
      .split(/[_\s]+/)
      .filter(Boolean)
      .map((word, i) => i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');

    if (msgpackArray && objectReceive.length > 0) {
      // ── Msgpack array-format decoding ──
      // Server sends events as positional arrays, not keyed maps.
      // Decode discriminator (first element) via unkeyedContainer, then
      // forward the container to the struct's init(from:inout UnkeyedDecodingContainer).

      lines.push('    public init(from decoder: Decoder) throws {');

      if (plainReceive.length > 0) {
        lines.push('        // Array-format discriminated decoding (msgpack)');
        lines.push('        // Try unkeyed container first; plain string messages fall through to catch.');
        lines.push('        do {');
        lines.push('            var container = try decoder.unkeyedContainer()');
        lines.push('            let type = try container.decode(String.self)');
        lines.push('');
        lines.push('            switch type {');
        for (const msg of objectReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`            case "${constVal}":`);
          lines.push(`                self = .${caseName}(try ${msg.swiftName}(from: &container))`);
        }
        lines.push('            default:');
        lines.push('                self = .unknown(type)');
        lines.push('            }');
        lines.push('        } catch {');
        lines.push('            // Plain string messages (no array structure)');
        lines.push('            let container = try decoder.singleValueContainer()');
        lines.push('            let value = try container.decode(String.self)');
        lines.push('            switch value {');
        for (const msg of plainReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`            case "${constVal}":`);
          lines.push(`                self = .${caseName}(value)`);
        }
        lines.push('            default:');
        lines.push('                self = .unknown(value)');
        lines.push('            }');
        lines.push('        }');
        lines.push('    }');
      } else {
        lines.push('        // Array-format discriminated decoding (msgpack)');
        lines.push('        var container = try decoder.unkeyedContainer()');
        lines.push('        let type = try container.decode(String.self)');
        lines.push('');
        lines.push('        switch type {');
        for (const msg of objectReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`        case "${constVal}":`);
          lines.push(`            self = .${caseName}(try ${msg.swiftName}(from: &container))`);
        }
        lines.push('        default:');
        lines.push('            self = .unknown(type)');
        lines.push('        }');
        lines.push('    }');
      }
    } else {
      // ── Standard keyed-container decoding (JSON / maps) ──

      if (objectReceive.length > 0) {
        lines.push('    private enum TypeKey: String, CodingKey {');
        if (swiftKeyName !== discriminatorKey) {
          lines.push(`        case ${swiftKeyName} = "${discriminatorKey}"`);
        } else {
          lines.push(`        case ${swiftKeyName}`);
        }
        lines.push('    }');
        lines.push('');
      }
      lines.push('    public init(from decoder: Decoder) throws {');

      if (plainReceive.length > 0 && objectReceive.length > 0) {
        // Try keyed container first (common case); plain string messages fall through to catch.
        lines.push('        do {');
        lines.push('            let container = try decoder.container(keyedBy: TypeKey.self)');
        lines.push(`            let type = try container.decode(String.self, forKey: .${swiftKeyName})`);
        lines.push('');
        lines.push('            switch type {');
        for (const msg of objectReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`            case "${constVal}":`);
          lines.push(`                self = .${caseName}(try ${msg.swiftName}(from: decoder))`);
        }
        lines.push('            default:');
        lines.push('                self = .unknown(type)');
        lines.push('            }');
        lines.push('        } catch {');
        lines.push('            // Plain string messages (no keyed structure)');
        lines.push('            let container = try decoder.singleValueContainer()');
        lines.push('            let value = try container.decode(String.self)');
        lines.push('            switch value {');
        for (const msg of plainReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`            case "${constVal}":`);
          lines.push(`                self = .${caseName}(value)`);
        }
        lines.push('            default:');
        lines.push('                self = .unknown(value)');
        lines.push('            }');
        lines.push('        }');
      } else if (objectReceive.length > 0) {
        lines.push('        let container = try decoder.container(keyedBy: TypeKey.self)');
        lines.push(`        let type = try container.decode(String.self, forKey: .${swiftKeyName})`);
        lines.push('');
        lines.push('        switch type {');
        for (const msg of objectReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`        case "${constVal}":`);
          lines.push(`            self = .${caseName}(try ${msg.swiftName}(from: decoder))`);
        }
        lines.push('        default:');
        lines.push('            self = .unknown(type)');
        lines.push('        }');
      } else {
        lines.push('        let container = try decoder.singleValueContainer()');
        lines.push('        let value = try container.decode(String.self)');
        lines.push('        switch value {');
        for (const msg of plainReceive) {
          const caseName = toSwiftEnumCase(msg.messageName);
          const constVal = msg.constTypeValue || msg.messageName;
          lines.push(`        case "${constVal}":`);
          lines.push(`            self = .${caseName}(value)`);
        }
        lines.push('        default:');
        lines.push('            self = .unknown(value)');
        lines.push('        }');
      }
      lines.push('    }');
    }
    lines.push('}');
  }

  return (
    <File name="Sources/MessageEnums.swift">
      <Text>{lines.join('\n')}</Text>
    </File>
  );
}

module.exports = MessageEnums;
