// template/MessageEnums.js — Generates IncomingMessage and OutgoingMessage tagged enums

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { toSwiftEnumCase, prefixedName, setTypePrefix } = require('../helpers/swift');
const { extractMessages } = require('../helpers/schema');

function MessageEnums({ asyncapi, params }) {
  setTypePrefix(params?.typePrefix);
  const allMessages = extractMessages(asyncapi);

  const sendMessages = allMessages.filter(m => m.direction === 'send');
  const receiveMessages = allMessages.filter(m => m.direction === 'receive');

  const outgoingName = prefixedName('OutgoingMessage');
  const incomingName = prefixedName('IncomingMessage');

  const lines = [];
  lines.push('// Generated by asyncapi-swift-ws-template — do not edit');
  lines.push('import Foundation');
  lines.push('');

  // ── OutgoingMessage ──
  if (sendMessages.length > 0) {
    lines.push('/// Messages the client can send to the server.');
    lines.push(`public enum ${outgoingName}: Sendable {`);
    for (const msg of sendMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      lines.push(`    case ${caseName}(${msg.swiftName})`);
    }
    lines.push('}');
    lines.push('');

    // Encodable conformance
    lines.push(`extension ${outgoingName}: Encodable {`);
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push('        switch self {');
    for (const msg of sendMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      lines.push(`        case .${caseName}(let value):`);
      lines.push('            try value.encode(to: encoder)');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  // ── IncomingMessage ──
  if (receiveMessages.length > 0) {
    lines.push('/// Messages the client can receive from the server.');
    lines.push(`public enum ${incomingName}: Sendable {`);
    for (const msg of receiveMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      lines.push(`    case ${caseName}(${msg.swiftName})`);
    }
    lines.push('    case unknown(String)');
    lines.push('}');
    lines.push('');

    // Decodable conformance — discriminated on `type` field
    lines.push(`extension ${incomingName}: Decodable {`);
    lines.push('    private enum TypeKey: String, CodingKey {');
    lines.push('        case type');
    lines.push('    }');
    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        let container = try decoder.container(keyedBy: TypeKey.self)');
    lines.push('        let type = try container.decode(String.self, forKey: .type)');
    lines.push('');
    lines.push('        switch type {');
    for (const msg of receiveMessages) {
      const caseName = toSwiftEnumCase(msg.messageName);
      const constVal = msg.constTypeValue || msg.messageName;
      lines.push(`        case "${constVal}":`);
      lines.push(`            self = .${caseName}(try ${msg.swiftName}(from: decoder))`);
    }
    lines.push('        default:');
    lines.push('            self = .unknown(type)');
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
  }

  return (
    <File name="Sources/MessageEnums.swift">
      <Text>{lines.join('\n')}</Text>
    </File>
  );
}

module.exports = MessageEnums;
