// template/Models.js — Generates Swift struct for each message payload and component schema

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { toSwiftTypeName, toSwiftPropertyName, toSwiftEnumCase, jsonSchemaTypeToSwift, setTypePrefix } = require('../helpers/swift');
const { extractMessages, extractSchemas, extractEnums, buildPropertyList } = require('../helpers/schema');

/**
 * Render a single Swift struct from a list of properties.
 */
function renderStruct(swiftName, properties, description) {
  const lines = [];

  if (description) {
    lines.push(`/// ${description.split('\n')[0]}`);
  }
  lines.push(`public struct ${swiftName}: Codable, Sendable {`);

  // Properties
  for (const prop of properties) {
    if (prop.isConst) {
      // Const fields: still decode them but provide a default
      lines.push(`    public let ${prop.swiftName}: String`);
    } else {
      lines.push(`    public let ${prop.swiftName}: ${prop.swiftType}`);
    }
  }

  // CodingKeys
  const needsKeys = properties.some(p => {
    const clean = p.swiftName.replace(/`/g, '');
    return clean !== p.wireFormat;
  });

  if (needsKeys) {
    lines.push('');
    lines.push('    private enum CodingKeys: String, CodingKey {');
    for (const prop of properties) {
      const clean = prop.swiftName.replace(/`/g, '');
      if (clean !== prop.wireFormat) {
        lines.push(`        case ${prop.swiftName} = "${prop.wireFormat}"`);
      } else {
        lines.push(`        case ${prop.swiftName}`);
      }
    }
    lines.push('    }');
  }

  // Public init — Swift auto-generated memberwise init is internal
  const initParams = properties.filter(p => !p.isConst);

  if (initParams.length > 0 || properties.some(p => p.isConst)) {
    lines.push('');
    if (initParams.length > 0) {
      lines.push('    public init(');
      for (let i = 0; i < initParams.length; i++) {
        const p = initParams[i];
        const hasDefault = p.swiftType.endsWith('?');
        const suffix = i < initParams.length - 1 ? ',' : '';
        lines.push(`        ${p.swiftName}: ${p.swiftType}${hasDefault ? ' = nil' : ''}${suffix}`);
      }
      lines.push('    ) {');
    } else {
      lines.push('    public init() {');
    }
    for (const prop of properties) {
      if (prop.isConst) {
        const escaped = String(prop.constVal != null ? prop.constVal : '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        lines.push(`        self.${prop.swiftName} = "${escaped}"`);
      } else {
        lines.push(`        self.${prop.swiftName} = ${prop.swiftName}`);
      }
    }
    lines.push('    }');
  }

  lines.push('}');

  return lines.join('\n');
}

function Models({ asyncapi, params }) {
  setTypePrefix(params?.typePrefix);
  const messages = extractMessages(asyncapi);
  const schemas = extractSchemas(asyncapi);
  const enumDefs = extractEnums(asyncapi);
  const renderedStructs = [];
  const generatedNames = new Set();

  // Generate structs for each message payload
  for (const msg of messages) {
    if (!msg.payload) continue;
    if (generatedNames.has(msg.swiftName)) continue;
    generatedNames.add(msg.swiftName);

    const properties = buildPropertyList(msg.payload, msg.swiftName, enumDefs);
    if (properties.length === 0) continue;

    const desc = msg.title || msg.summary || '';
    renderedStructs.push(renderStruct(msg.swiftName, properties, desc));
  }

  // Generate structs for component schemas
  for (const sch of schemas) {
    if (generatedNames.has(sch.swiftName)) continue;
    generatedNames.add(sch.swiftName);

    const properties = buildPropertyList(sch.schema, sch.swiftName, enumDefs);
    if (properties.length === 0) continue;

    renderedStructs.push(renderStruct(sch.swiftName, properties, ''));
  }

  if (renderedStructs.length === 0) return null;

  return (
    <File name="Sources/Models.swift">
      <Text>{`// Generated by asyncapi-swift-ws-template — do not edit
import Foundation

${renderedStructs.join('\n\n')}`}</Text>
    </File>
  );
}

module.exports = Models;
