// template/Serializer.js — Generates MessageSerializer protocol and implementations

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { prefixedName, setTypePrefix } = require('../helpers/swift');

function Serializer({ params }) {
  setTypePrefix(params?.typePrefix);
  const useMsgpack = params.serialization === 'msgpack';
  const protocolName = prefixedName('MessageSerializer');
  const jsonName = prefixedName('JSONMessageSerializer');
  const msgpackName = prefixedName('MessagePackSerializer');

  const lines = [];
  lines.push('// Generated by asyncapi-swift-ws-template — do not edit');
  lines.push('import Foundation');
  if (useMsgpack) {
    lines.push('import MessagePack');
  }
  lines.push('');

  // Protocol
  lines.push('/// Abstraction over wire serialization format.');
  lines.push(`public protocol ${protocolName}: Sendable {`);
  lines.push('    func encode<T: Encodable>(_ value: T) throws -> Data');
  lines.push('    func decode<T: Decodable>(_ type: T.Type, from data: Data) throws -> T');
  lines.push('}');
  lines.push('');

  // JSON implementation
  lines.push('/// JSON serializer using Foundation JSONEncoder/JSONDecoder.');
  lines.push(`public struct ${jsonName}: ${protocolName} {`);
  lines.push('    private let encoder = JSONEncoder()');
  lines.push('    private let decoder = JSONDecoder()');
  lines.push('');
  lines.push('    public init() {}');
  lines.push('');
  lines.push('    public func encode<T: Encodable>(_ value: T) throws -> Data {');
  lines.push('        try encoder.encode(value)');
  lines.push('    }');
  lines.push('');
  lines.push('    public func decode<T: Decodable>(_ type: T.Type, from data: Data) throws -> T {');
  lines.push('        try decoder.decode(type, from: data)');
  lines.push('    }');
  lines.push('}');

  // MessagePack implementation
  if (useMsgpack) {
    lines.push('');
    lines.push('/// MessagePack serializer using msgpack-swift.');
    lines.push(`public struct ${msgpackName}: ${protocolName} {`);
    lines.push('    public init() {}');
    lines.push('');
    lines.push('    public func encode<T: Encodable>(_ value: T) throws -> Data {');
    lines.push('        try MessagePackEncoder().encode(value)');
    lines.push('    }');
    lines.push('');
    lines.push('    public func decode<T: Decodable>(_ type: T.Type, from data: Data) throws -> T {');
    lines.push('        try MessagePackDecoder().decode(type, from: data)');
    lines.push('    }');
    lines.push('}');
  }

  return (
    <File name="Sources/MessageSerializer.swift">
      <Text>{lines.join('\n')}</Text>
    </File>
  );
}

module.exports = Serializer;
