// template/WebSocketClient.js — Generates the actor-based WebSocket client

const { File, Text } = require('@asyncapi/generator-react-sdk');
const { derivePackageName, prefixedName, setTypePrefix } = require('../helpers/swift');
const { buildServerURL } = require('../helpers/schema');

function WebSocketClient({ asyncapi, params }) {
  setTypePrefix(params?.typePrefix);
  const serverInfo = buildServerURL(asyncapi, params.server);
  const useMsgpack = params.serialization === 'msgpack';
  const reconnect = params.reconnect !== 'false';

  const connStateName = prefixedName('ConnectionState');
  const configName = prefixedName('ClientConfiguration');
  const clientName = prefixedName('WebSocketClient');
  const errorName = prefixedName('WebSocketClientError');
  const serializerProto = prefixedName('MessageSerializer');
  const jsonSerializer = prefixedName('JSONMessageSerializer');
  const msgpackSerializer = prefixedName('MessagePackSerializer');
  const incomingName = prefixedName('IncomingMessage');
  const outgoingName = prefixedName('OutgoingMessage');
  const defaultSerializer = useMsgpack ? `${msgpackSerializer}()` : `${jsonSerializer}()`;

  const lines = [];
  lines.push('// Generated by asyncapi-swift-ws-template — do not edit');
  lines.push('import Foundation');
  lines.push('');

  // ── ConnectionState ──
  lines.push('/// Represents the state of the WebSocket connection.');
  lines.push(`public enum ${connStateName}: Sendable, Equatable {`);
  lines.push('    case disconnected');
  lines.push('    case connecting');
  lines.push('    case connected');
  if (reconnect) {
    lines.push('    case reconnecting(attempt: Int)');
  }
  lines.push('}');
  lines.push('');

  // ── Configuration ──
  lines.push('/// Configuration for the WebSocket client.');
  lines.push(`public struct ${configName}: Sendable {`);
  lines.push('    public let url: URL');
  lines.push('    public let headers: [String: String]');
  lines.push(`    public let serializer: ${serializerProto}`);
  if (reconnect) {
    lines.push('    public let autoReconnect: Bool');
    lines.push('    public let maxReconnectAttempts: Int');
    lines.push('    public let baseReconnectDelay: TimeInterval');
  }
  lines.push('    public let pingInterval: TimeInterval?');
  lines.push('');
  lines.push('    public init(');
  lines.push(`        url: URL${serverInfo ? ` = URL(string: "${serverInfo.url}")!` : ''},`);
  lines.push('        headers: [String: String] = [:],');
  lines.push(`        serializer: ${serializerProto} = ${defaultSerializer},`);
  if (reconnect) {
    lines.push('        autoReconnect: Bool = false,');
    lines.push('        maxReconnectAttempts: Int = 10,');
    lines.push('        baseReconnectDelay: TimeInterval = 1.0,');
  }
  lines.push('        pingInterval: TimeInterval? = 30.0');
  lines.push('    ) {');
  lines.push('        self.url = url');
  lines.push('        self.headers = headers');
  lines.push('        self.serializer = serializer');
  if (reconnect) {
    lines.push('        self.autoReconnect = autoReconnect');
    lines.push('        self.maxReconnectAttempts = maxReconnectAttempts');
    lines.push('        self.baseReconnectDelay = baseReconnectDelay');
  }
  lines.push('        self.pingInterval = pingInterval');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // ── WebSocketClient actor ──
  lines.push('/// Actor-based WebSocket client with typed message send/receive.');
  lines.push(`public actor ${clientName} {`);
  lines.push(`    private let configuration: ${configName}`);
  lines.push('    private let session: URLSession');
  lines.push('    private var webSocketTask: URLSessionWebSocketTask?');
  lines.push('    private var receiveTask: Task<Void, Never>?');
  lines.push('    private var pingTask: Task<Void, Never>?');
  if (reconnect) {
    lines.push('    private var reconnectTask: Task<Void, Never>?');
    lines.push('    private var reconnectAttempt = 0');
    lines.push('    private var intentionalDisconnect = false');
  }
  lines.push('');
  lines.push(`    private var messageContinuation: AsyncStream<${incomingName}>.Continuation?`);
  lines.push(`    private var stateContinuation: AsyncStream<${connStateName}>.Continuation?`);
  lines.push('');
  lines.push('    /// Stream of incoming messages from the server.');
  lines.push(`    public let messages: AsyncStream<${incomingName}>`);
  lines.push('    /// Stream of connection state changes.');
  lines.push(`    public let connectionState: AsyncStream<${connStateName}>`);
  lines.push('');
  lines.push(`    private var _currentState: ${connStateName} = .disconnected {`);
  lines.push('        didSet { stateContinuation?.yield(_currentState) }');
  lines.push('    }');
  lines.push('');

  // init
  lines.push(`    public init(configuration: ${configName} = ${configName}()) {`);
  lines.push('        self.configuration = configuration');
  lines.push('        self.session = URLSession(configuration: .default)');
  lines.push('');
  lines.push(`        var msgCont: AsyncStream<${incomingName}>.Continuation!`);
  lines.push('        self.messages = AsyncStream { msgCont = $0 }');
  lines.push('        self.messageContinuation = msgCont');
  lines.push('');
  lines.push(`        var stateCont: AsyncStream<${connStateName}>.Continuation!`);
  lines.push('        self.connectionState = AsyncStream { stateCont = $0 }');
  lines.push('        self.stateContinuation = stateCont');
  lines.push('    }');
  lines.push('');

  // connect
  lines.push('    /// Connect to the WebSocket server.');
  lines.push('    public func connect() {');
  lines.push('        _currentState = .connecting');
  if (reconnect) {
    lines.push('        intentionalDisconnect = false');
  }
  lines.push('');
  lines.push('        var request = URLRequest(url: configuration.url)');
  lines.push('        for (key, value) in configuration.headers {');
  lines.push('            request.setValue(value, forHTTPHeaderField: key)');
  lines.push('        }');
  lines.push('');
  lines.push('        let task = session.webSocketTask(with: request)');
  lines.push('        webSocketTask = task');
  lines.push('        task.resume()');
  lines.push('        startReceiving()');
  lines.push('        startPinging()');
  lines.push('    }');
  lines.push('');

  // disconnect
  lines.push('    /// Disconnect from the WebSocket server.');
  lines.push('    public func disconnect() {');
  if (reconnect) {
    lines.push('        intentionalDisconnect = true');
    lines.push('        reconnectTask?.cancel()');
    lines.push('        reconnectTask = nil');
  }
  lines.push('        receiveTask?.cancel()');
  lines.push('        receiveTask = nil');
  lines.push('        pingTask?.cancel()');
  lines.push('        pingTask = nil');
  lines.push('        webSocketTask?.cancel(with: .normalClosure, reason: nil)');
  lines.push('        webSocketTask = nil');
  lines.push('        _currentState = .disconnected');
  lines.push('    }');
  lines.push('');

  // send
  lines.push('    /// Send a typed message to the server.');
  lines.push(`    public func send(_ message: ${outgoingName}) async throws {`);
  lines.push('        guard let task = webSocketTask else {');
  lines.push(`            throw ${errorName}.notConnected`);
  lines.push('        }');
  lines.push('        let data = try configuration.serializer.encode(message)');
  if (useMsgpack) {
    lines.push('        try await task.send(.data(data))');
  } else {
    lines.push('        let string = String(data: data, encoding: .utf8) ?? ""');
    lines.push('        try await task.send(.string(string))');
  }
  lines.push('    }');
  lines.push('');

  // startReceiving
  lines.push('    private func startReceiving() {');
  lines.push('        receiveTask?.cancel()');
  lines.push('        receiveTask = Task { [weak self] in');
  lines.push('            guard let self else { return }');
  lines.push('            await self.receiveLoop()');
  lines.push('        }');
  lines.push('    }');
  lines.push('');

  lines.push('    private func receiveLoop() async {');
  lines.push('        while !Task.isCancelled {');
  lines.push('            guard let task = webSocketTask else { break }');
  lines.push('            do {');
  lines.push('                let message = try await task.receive()');
  if (reconnect) {
    lines.push('                if _currentState != .connected {');
    lines.push('                    _currentState = .connected');
    lines.push('                    reconnectAttempt = 0');
    lines.push('                }');
  } else {
    lines.push('                if _currentState != .connected { _currentState = .connected }');
  }
  lines.push('                let data: Data');
  lines.push('                switch message {');
  lines.push('                case .string(let text):');
  lines.push('                    data = Data(text.utf8)');
  lines.push('                case .data(let binary):');
  lines.push('                    data = binary');
  lines.push('                @unknown default:');
  lines.push('                    continue');
  lines.push('                }');
  lines.push('                do {');
  lines.push(`                    let incoming = try configuration.serializer.decode(${incomingName}.self, from: data)`);
  lines.push('                    messageContinuation?.yield(incoming)');
  lines.push('                } catch {');
  lines.push('                    // Decoding error — skip malformed message');
  lines.push('                }');
  lines.push('            } catch {');
  lines.push('                // Connection error');
  lines.push('                break');
  lines.push('            }');
  lines.push('        }');

  if (reconnect) {
    lines.push('        // Connection lost — attempt reconnect if appropriate');
    lines.push('        if !intentionalDisconnect {');
    lines.push('            await handleDisconnect()');
    lines.push('        }');
  } else {
    lines.push('        _currentState = .disconnected');
  }
  lines.push('    }');
  lines.push('');

  // startPinging
  lines.push('    private func startPinging() {');
  lines.push('        guard let interval = configuration.pingInterval else { return }');
  lines.push('        pingTask?.cancel()');
  lines.push('        pingTask = Task { [weak self] in');
  lines.push('            while !Task.isCancelled {');
  lines.push('                try? await Task.sleep(for: .seconds(interval))');
  lines.push('                guard let self, let task = await self.webSocketTask else { break }');
  lines.push('                task.sendPing { _ in }');
  lines.push('            }');
  lines.push('        }');
  lines.push('    }');

  // reconnect logic
  if (reconnect) {
    lines.push('');
    lines.push('    private func handleDisconnect() async {');
    lines.push('        guard configuration.autoReconnect,');
    lines.push('              reconnectAttempt < configuration.maxReconnectAttempts else {');
    lines.push('            _currentState = .disconnected');
    lines.push('            return');
    lines.push('        }');
    lines.push('');
    lines.push('        reconnectAttempt += 1');
    lines.push('        _currentState = .reconnecting(attempt: reconnectAttempt)');
    lines.push('');
    lines.push('        let delay = configuration.baseReconnectDelay * pow(2.0, Double(reconnectAttempt - 1))');
    lines.push('        let jittered = min(delay, 60.0) * Double.random(in: 0.8...1.2)');
    lines.push('');
    lines.push('        try? await Task.sleep(for: .seconds(jittered))');
    lines.push('');
    lines.push('        guard !intentionalDisconnect, !Task.isCancelled else { return }');
    lines.push('        connect()');
    lines.push('    }');
  }

  lines.push('');
  lines.push('    deinit {');
  lines.push('        receiveTask?.cancel()');
  lines.push('        pingTask?.cancel()');
  if (reconnect) {
    lines.push('        reconnectTask?.cancel()');
  }
  lines.push('        webSocketTask?.cancel(with: .normalClosure, reason: nil)');
  lines.push('    }');
  lines.push('}');
  lines.push('');

  // Error enum
  lines.push(`/// Errors thrown by ${clientName}.`);
  lines.push(`public enum ${errorName}: Swift.Error, Sendable {`);
  lines.push('    case notConnected');
  lines.push('}');

  return (
    <File name="Sources/WebSocketClient.swift">
      <Text>{lines.join('\n')}</Text>
    </File>
  );
}

module.exports = WebSocketClient;
