// test/generate.test.js — End-to-end tests for Swift output generation
//
// Run with: node --test test/generate.test.js
//
// These tests generate Swift code from fixture AsyncAPI specs and assert
// on file structure, naming conventions, type correctness, and parameter behavior.

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const { generate, readGenerated, generatedFileExists, listGeneratedSwiftFiles, cleanOutput } = require('./helpers');

// ─────────────────────────────────────────────────────────────────────────────
// Basic spec — minimal send/receive with no enums, no $ref, no msgpack
// ─────────────────────────────────────────────────────────────────────────────

describe('basic spec (JSON, reconnect, no prefix)', () => {
  let out;

  before(() => {
    out = generate('basic.asyncapi.yaml', { server: 'local' });
  });

  // ── File structure ──

  it('generates Package.swift', () => {
    assert.ok(generatedFileExists(out, 'Package.swift'));
  });

  it('generates all expected Swift source files', () => {
    const files = listGeneratedSwiftFiles(out);
    assert.ok(files.includes('Models.swift'), 'missing Models.swift');
    assert.ok(files.includes('MessageEnums.swift'), 'missing MessageEnums.swift');
    assert.ok(files.includes('MessageSerializer.swift'), 'missing MessageSerializer.swift');
    assert.ok(files.includes('WebSocketClient.swift'), 'missing WebSocketClient.swift');
  });

  it('does not generate Enums.swift when spec has no enums', () => {
    assert.ok(!generatedFileExists(out, 'Sources/Enums.swift'));
  });

  // ── Package.swift ──

  describe('Package.swift', () => {
    let pkg;
    before(() => { pkg = readGenerated(out, 'Package.swift'); });

    it('uses swift-tools-version 6.0', () => {
      assert.ok(pkg.startsWith('// swift-tools-version: 6.0'));
    });

    it('imports PackageDescription', () => {
      assert.ok(pkg.includes('import PackageDescription'));
    });

    it('derives package name from spec title', () => {
      assert.ok(pkg.includes('name: "TestBasicWS"'));
    });

    it('does not include msgpack dependency', () => {
      assert.ok(!pkg.includes('msgpack-swift'));
      assert.ok(!pkg.includes('DMMessagePack'));
    });

    it('targets Apple platforms', () => {
      assert.ok(pkg.includes('.iOS('));
      assert.ok(pkg.includes('.macOS('));
    });
  });

  // ── Models.swift ──

  describe('Models.swift', () => {
    let models;
    before(() => { models = readGenerated(out, 'Sources/Models.swift'); });

    it('has generation header', () => {
      assert.ok(models.includes('// Generated by asyncapi-swift-ws-template'));
    });

    it('imports Foundation', () => {
      assert.ok(models.includes('import Foundation'));
    });

    it('generates Codable & Sendable structs for send messages', () => {
      assert.ok(models.includes('public struct Ping: Codable, Sendable'));
      assert.ok(models.includes('public struct Echo: Codable, Sendable'));
    });

    it('generates Codable & Sendable structs for receive messages', () => {
      assert.ok(models.includes('public struct Pong: Codable, Sendable'));
      assert.ok(models.includes('public struct EchoReply: Codable, Sendable'));
      assert.ok(models.includes('public struct ServerError: Codable, Sendable'));
    });

    it('uses public let for properties', () => {
      assert.ok(models.includes('public let message: String'));
    });

    it('generates CodingKeys for snake_case properties', () => {
      assert.ok(models.includes('case serverTime = "server_time"'));
    });

    it('handles Error → ServerError reserved type rename', () => {
      assert.ok(models.includes('public struct ServerError: Codable, Sendable'));
      assert.ok(!models.includes('public struct Error:'));
    });
  });

  // ── MessageEnums.swift ──

  describe('MessageEnums.swift', () => {
    let enums;
    before(() => { enums = readGenerated(out, 'Sources/MessageEnums.swift'); });

    it('defines OutgoingMessage enum', () => {
      assert.ok(enums.includes('public enum OutgoingMessage: Sendable'));
    });

    it('defines IncomingMessage enum', () => {
      assert.ok(enums.includes('public enum IncomingMessage: Sendable'));
    });

    it('has outgoing cases for send messages', () => {
      assert.ok(enums.includes('case ping(Ping)'));
      assert.ok(enums.includes('case echo(Echo)'));
    });

    it('has incoming cases for receive messages', () => {
      assert.ok(enums.includes('case pong(Pong)'));
      assert.ok(enums.includes('case echoReply(EchoReply)'));
    });

    it('has unknown case for unrecognized incoming messages', () => {
      assert.ok(enums.includes('case unknown(String)'));
    });

    it('makes OutgoingMessage Encodable', () => {
      assert.ok(enums.includes('extension OutgoingMessage: Encodable'));
    });

    it('makes IncomingMessage Decodable', () => {
      assert.ok(enums.includes('extension IncomingMessage: Decodable'));
    });

    it('decodes on the type discriminator field', () => {
      assert.ok(enums.includes('case type'));
      assert.ok(enums.includes('TypeKey'));
    });
  });

  // ── MessageSerializer.swift ──

  describe('MessageSerializer.swift', () => {
    let ser;
    before(() => { ser = readGenerated(out, 'Sources/MessageSerializer.swift'); });

    it('defines MessageSerializer protocol', () => {
      assert.ok(ser.includes('public protocol MessageSerializer: Sendable'));
    });

    it('defines JSONMessageSerializer', () => {
      assert.ok(ser.includes('public struct JSONMessageSerializer: MessageSerializer'));
    });

    it('does not generate MessagePackSerializer', () => {
      assert.ok(!ser.includes('MessagePackSerializer'));
      assert.ok(!ser.includes('import MessagePack'));
    });
  });

  // ── WebSocketClient.swift ──

  describe('WebSocketClient.swift', () => {
    let client;
    before(() => { client = readGenerated(out, 'Sources/WebSocketClient.swift'); });

    it('defines ConnectionState enum', () => {
      assert.ok(client.includes('public enum ConnectionState: Sendable, Equatable'));
    });

    it('includes reconnecting state by default', () => {
      assert.ok(client.includes('case reconnecting(attempt: Int)'));
    });

    it('defines ClientConfiguration struct', () => {
      assert.ok(client.includes('public struct ClientConfiguration: Sendable'));
    });

    it('defines WebSocketClient actor', () => {
      assert.ok(client.includes('public actor WebSocketClient'));
    });

    it('defines error enum using Swift.Error', () => {
      assert.ok(client.includes('public enum WebSocketClientError: Swift.Error, Sendable'));
    });

    it('includes default URL from server config', () => {
      assert.ok(client.includes('ws://localhost:9000'));
    });

    it('has auto-reconnect config fields', () => {
      assert.ok(client.includes('autoReconnect'));
      assert.ok(client.includes('maxReconnectAttempts'));
      assert.ok(client.includes('baseReconnectDelay'));
    });

    it('uses AsyncStream for messages', () => {
      assert.ok(client.includes('AsyncStream<IncomingMessage>'));
    });

    it('uses AsyncStream for state', () => {
      assert.ok(client.includes('AsyncStream<ConnectionState>'));
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Enums, $ref resolution, and reserved word handling
// ─────────────────────────────────────────────────────────────────────────────

describe('enums-and-refs spec', () => {
  let out;

  before(() => {
    out = generate('enums-and-refs.asyncapi.yaml', { server: 'local' });
  });

  it('generates Enums.swift', () => {
    assert.ok(generatedFileExists(out, 'Sources/Enums.swift'));
  });

  describe('Enums.swift', () => {
    let enums;
    before(() => { enums = readGenerated(out, 'Sources/Enums.swift'); });

    it('generates Priority enum', () => {
      assert.ok(enums.includes('public enum Priority: String, Codable, Sendable'));
    });

    it('Priority has all expected cases', () => {
      assert.ok(enums.includes('case low'));
      assert.ok(enums.includes('case medium'));
      assert.ok(enums.includes('case high'));
      assert.ok(enums.includes('case critical'));
    });

    it('generates a status enum (deduped)', () => {
      // The status and new_status properties share the same values.
      // Only one enum should exist for this set of values.
      const enumCount = (enums.match(/public enum \w+: String, Codable, Sendable/g) || []).length;
      assert.equal(enumCount, 2, 'should have exactly 2 enums (priority + status)');
    });

    it('status enum has correct cases', () => {
      assert.ok(enums.includes('case pending'));
      assert.ok(enums.includes('case active'));
      assert.ok(enums.includes('case archived'));
    });
  });

  describe('Models.swift — $ref resolution', () => {
    let models;
    before(() => { models = readGenerated(out, 'Sources/Models.swift'); });

    it('generates ItemData struct from component schema', () => {
      assert.ok(models.includes('public struct ItemData: Codable, Sendable'));
    });

    it('resolves $ref in ItemCreated to ItemData type', () => {
      assert.ok(models.includes('public let item: ItemData'));
    });

    it('resolves array $ref in ItemList to [ItemData]', () => {
      assert.ok(models.includes('public let items: [ItemData]'));
    });

    it('renames Error schema to ServerError', () => {
      assert.ok(models.includes('public struct ServerError: Codable, Sendable'));
      assert.ok(!models.includes('public struct Error:'));
    });
  });

  describe('Models.swift — property types', () => {
    let models;
    before(() => { models = readGenerated(out, 'Sources/Models.swift'); });

    it('uses enum types for enum properties', () => {
      assert.ok(models.includes(': Priority'));
    });

    it('handles CodingKeys for snake_case fields', () => {
      assert.ok(models.includes('case itemId = "item_id"'));
    });

    it('makes non-required properties optional', () => {
      // item in ItemCreated is not required
      assert.ok(models.includes('public let item: ItemData?'));
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// MessagePack serialization
// ─────────────────────────────────────────────────────────────────────────────

describe('msgpack spec (serialization=msgpack)', () => {
  let out;

  before(() => {
    out = generate('msgpack.asyncapi.yaml', { server: 'local', serialization: 'msgpack' });
  });

  describe('Package.swift', () => {
    let pkg;
    before(() => { pkg = readGenerated(out, 'Package.swift'); });

    it('includes msgpack-swift dependency', () => {
      assert.ok(pkg.includes('msgpack-swift.git'));
    });

    it('includes DMMessagePack product', () => {
      assert.ok(pkg.includes('DMMessagePack'));
    });
  });

  describe('MessageSerializer.swift', () => {
    let ser;
    before(() => { ser = readGenerated(out, 'Sources/MessageSerializer.swift'); });

    it('imports MessagePack', () => {
      assert.ok(ser.includes('import MessagePack'));
    });

    it('generates MessagePackSerializer', () => {
      assert.ok(ser.includes('public struct MessagePackSerializer: MessageSerializer'));
    });

    it('still generates JSONMessageSerializer', () => {
      assert.ok(ser.includes('public struct JSONMessageSerializer: MessageSerializer'));
    });
  });

  describe('WebSocketClient.swift', () => {
    let client;
    before(() => { client = readGenerated(out, 'Sources/WebSocketClient.swift'); });

    it('defaults to MessagePackSerializer', () => {
      assert.ok(client.includes('MessagePackSerializer()'));
    });

    it('uses wss:// URL for wss protocol', () => {
      assert.ok(client.includes('wss://localhost:9002'));
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// reconnect=false
// ─────────────────────────────────────────────────────────────────────────────

describe('reconnect=false', () => {
  let out;

  before(() => {
    out = generate('basic.asyncapi.yaml', { server: 'local', reconnect: 'false' });
  });

  describe('WebSocketClient.swift', () => {
    let client;
    before(() => { client = readGenerated(out, 'Sources/WebSocketClient.swift'); });

    it('does not include reconnecting state', () => {
      assert.ok(!client.includes('reconnecting'));
    });

    it('does not include autoReconnect config', () => {
      assert.ok(!client.includes('autoReconnect'));
    });

    it('does not include maxReconnectAttempts', () => {
      assert.ok(!client.includes('maxReconnectAttempts'));
    });

    it('does not include baseReconnectDelay', () => {
      assert.ok(!client.includes('baseReconnectDelay'));
    });

    it('still defines ConnectionState enum', () => {
      assert.ok(client.includes('public enum ConnectionState:'));
    });

    it('still has connected/disconnected/connecting states', () => {
      assert.ok(client.includes('case disconnected'));
      assert.ok(client.includes('case connecting'));
      assert.ok(client.includes('case connected'));
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// typePrefix parameter
// ─────────────────────────────────────────────────────────────────────────────

describe('typePrefix=TST', () => {
  let out;

  before(() => {
    out = generate('enums-and-refs.asyncapi.yaml', { server: 'local', typePrefix: 'TST' });
  });

  describe('Models.swift', () => {
    let models;
    before(() => { models = readGenerated(out, 'Sources/Models.swift'); });

    it('prefixes all struct names', () => {
      assert.ok(models.includes('public struct TSTCreateItem:'));
      assert.ok(models.includes('public struct TSTItemCreated:'));
      assert.ok(models.includes('public struct TSTItemData:'));
      assert.ok(models.includes('public struct TSTServerError:'));
    });

    it('does not contain unprefixed struct names', () => {
      assert.ok(!models.match(/public struct (?!TST)\w+:/));
    });

    it('prefixes $ref type references', () => {
      assert.ok(models.includes(': TSTItemData'));
    });
  });

  describe('Enums.swift', () => {
    let enums;
    before(() => { enums = readGenerated(out, 'Sources/Enums.swift'); });

    it('prefixes enum names', () => {
      assert.ok(enums.includes('public enum TSTPriority:'));
    });

    it('does not double-prefix', () => {
      assert.ok(!enums.includes('TSTTSTT'));
    });
  });

  describe('MessageEnums.swift', () => {
    let msgEnums;
    before(() => { msgEnums = readGenerated(out, 'Sources/MessageEnums.swift'); });

    it('prefixes OutgoingMessage and IncomingMessage', () => {
      assert.ok(msgEnums.includes('public enum TSTOutgoingMessage:'));
      assert.ok(msgEnums.includes('public enum TSTIncomingMessage:'));
    });

    it('uses prefixed struct types in cases', () => {
      assert.ok(msgEnums.includes('case createItem(TSTCreateItem)'));
    });
  });

  describe('MessageSerializer.swift', () => {
    let ser;
    before(() => { ser = readGenerated(out, 'Sources/MessageSerializer.swift'); });

    it('prefixes protocol and struct names', () => {
      assert.ok(ser.includes('public protocol TSTMessageSerializer:'));
      assert.ok(ser.includes('public struct TSTJSONMessageSerializer: TSTMessageSerializer'));
    });
  });

  describe('WebSocketClient.swift', () => {
    let client;
    before(() => { client = readGenerated(out, 'Sources/WebSocketClient.swift'); });

    it('prefixes all top-level types', () => {
      assert.ok(client.includes('public enum TSTConnectionState:'));
      assert.ok(client.includes('public struct TSTClientConfiguration:'));
      assert.ok(client.includes('public actor TSTWebSocketClient'));
      assert.ok(client.includes('public enum TSTWebSocketClientError:'));
    });

    it('references prefixed serializer types', () => {
      assert.ok(client.includes('TSTMessageSerializer'));
      assert.ok(client.includes('TSTJSONMessageSerializer'));
    });

    it('references prefixed message types', () => {
      assert.ok(client.includes('TSTIncomingMessage'));
      assert.ok(client.includes('TSTOutgoingMessage'));
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Custom package name
// ─────────────────────────────────────────────────────────────────────────────

describe('custom packageName', () => {
  let out;

  before(() => {
    out = generate('basic.asyncapi.yaml', { server: 'local', packageName: 'MyCustomClient' });
  });

  it('uses the custom package name', () => {
    const pkg = readGenerated(out, 'Package.swift');
    assert.ok(pkg.includes('name: "MyCustomClient"'));
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Combined parameters
// ─────────────────────────────────────────────────────────────────────────────

describe('combined params (msgpack + prefix + no reconnect)', () => {
  let out;

  before(() => {
    out = generate('msgpack.asyncapi.yaml', {
      server: 'local',
      serialization: 'msgpack',
      typePrefix: 'XYZ',
      reconnect: 'false',
    });
  });

  it('has prefixed msgpack serializer', () => {
    const ser = readGenerated(out, 'Sources/MessageSerializer.swift');
    assert.ok(ser.includes('public struct XYZMessagePackSerializer: XYZMessageSerializer'));
  });

  it('has no reconnect logic', () => {
    const client = readGenerated(out, 'Sources/WebSocketClient.swift');
    assert.ok(!client.includes('reconnecting'));
    assert.ok(!client.includes('autoReconnect'));
  });

  it('has prefixed client types', () => {
    const client = readGenerated(out, 'Sources/WebSocketClient.swift');
    assert.ok(client.includes('public actor XYZWebSocketClient'));
    assert.ok(client.includes('XYZMessagePackSerializer()'));
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Consistency checks
// ─────────────────────────────────────────────────────────────────────────────

describe('cross-file consistency', () => {
  let out;
  let models, msgEnums, client, ser;

  before(() => {
    out = generate('enums-and-refs.asyncapi.yaml', { server: 'local' });
    models = readGenerated(out, 'Sources/Models.swift');
    msgEnums = readGenerated(out, 'Sources/MessageEnums.swift');
    client = readGenerated(out, 'Sources/WebSocketClient.swift');
    ser = readGenerated(out, 'Sources/MessageSerializer.swift');
  });

  it('every struct referenced in MessageEnums exists in Models', () => {
    // Extract associated value types from enum cases, excluding String (unknown case)
    const caseTypes = [...msgEnums.matchAll(/case \w+\((\w+)\)/g)]
      .map(m => m[1])
      .filter(t => t !== 'String' && t !== 'Int');
    for (const type of caseTypes) {
      assert.ok(
        models.includes(`public struct ${type}:`),
        `MessageEnums references ${type} but it's not defined in Models.swift`
      );
    }
  });

  it('serializer protocol in client matches serializer file', () => {
    // Extract protocol name from serializer file
    const protoMatch = ser.match(/public protocol (\w+): Sendable/);
    assert.ok(protoMatch, 'no serializer protocol found');
    const protoName = protoMatch[1];
    assert.ok(client.includes(protoName), `client should reference ${protoName}`);
  });

  it('IncomingMessage name in client matches MessageEnums', () => {
    const inMatch = msgEnums.match(/public enum (\w*IncomingMessage):/);
    assert.ok(inMatch, 'no IncomingMessage enum found');
    assert.ok(client.includes(inMatch[1]), `client should reference ${inMatch[1]}`);
  });

  it('all generated Swift files have the generation header', () => {
    const files = listGeneratedSwiftFiles(out);
    for (const file of files) {
      const content = readGenerated(out, `Sources/${file}`);
      assert.ok(
        content.includes('// Generated by asyncapi-swift-ws-template'),
        `${file} missing generation header`
      );
    }
  });

  it('all generated Swift files import Foundation', () => {
    const files = listGeneratedSwiftFiles(out);
    for (const file of files) {
      const content = readGenerated(out, `Sources/${file}`);
      assert.ok(content.includes('import Foundation'), `${file} missing Foundation import`);
    }
  });
});
